### ISSUE TITLE
Support for Lemmy v0.19.4

### ISSUE THREAD

**Issue by etymotic** [RikudouSage/LemmySchedule#30]
Error fetching communities because of the new Community Visibility option in Lemmy 0.19.4.

`[warning] Error thrown while handling message App\Job\FetchCommunitiesJob. Sending for retry #1 using 1000 ms delay. Error: "Handling "App\Job\FetchCommunitiesJob" failed: Unknown named parameter $visibility"`

Also receiving an error (and a "500 Internal Server Error") when creating a post as follows:

```
[Mon Jun 10 13:20:53.788829 2024] [php:notice] [pid 41] [client 172.20.0.1:34704] [critical] Uncaught PHP Exception Error: "Unknown named parameter $visibility" at /var/www/html/vendor/rikudou/lemmy-api/src/Response/AbstractResponseDto.php line 104, referer: https://schedule.wetshaving.social/post/create
172.20.0.1 - - [10/Jun/2024:13:20:53 +0000] "POST /post/create/do HTTP/1.1" 500 1339 "https://schedule.wetshaving.social/post/create" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
```

**Comment by RikudouSage** [comment]
Should be fixed now.

**Comment by etymotic** [comment]
Getting a 500 Error when I click "Schedule a post".

Logs:
```

172.20.0.1 - - [13/Jun/2024:01:39:33 +0000] "GET /post/list HTTP/1.1" 200 2481 "https://schedule.wetshaving.social/post/list" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"
[Thu Jun 13 01:39:43.326975 2024] [php:notice] [pid 44] [client 172.20.0.1:54510] [critical] Uncaught PHP Exception Twig\\Error\\RuntimeError: "Error rendering "ScheduleComponent" component: Cannot assign null to property Symfony\\UX\\LiveComponent\\Twig\\TemplateMap::$map of type array" at /var/www/html/templates/post/create.html.twig line 201, referer: https://schedule.wetshaving.social/post/list
172.20.0.1 - - [13/Jun/2024:01:39:43 +0000] "GET /post/create HTTP/1.1" 500 1339 "https://schedule.wetshaving.social/post/list" "Mozilla/5.0 (X11; Linux x86_64; rv:126.0) Gecko/20100101 Firefox/126.0"

```

**Comment by RikudouSage** [comment]
Try backing up the cache directory and then deleting it.

**Comment by etymotic** [comment]
> Try backing up the cache directory and then deleting it.

I removed and recreated cache (and uploads). Docker changed the owner of those folders to www-data which I think is normal behavior?

I'm still getting the 500 error and

`[Thu Jun 13 18:09:04.715108 2024] [php:notice] [pid 41] [client 172.20.0.1:38010] [critical] Uncaught PHP Exception Twig\\Error\\RuntimeError: "Error rendering "ScheduleComponent" component: Cannot assign null to property Symfony\\UX\\LiveComponent\\Twig\\TemplateMap::$map of type array" at /var/www/html/templates/post/create.html.twig line 201, referer: https://schedule.wetshaving.social/post/list`

**Comment by etymotic** [comment]
Created a new issue since it's probably unrelated to this one 👍
